version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "80:80"      
    depends_on:
      - backend    
    restart: always
